[package]
name = "chameleon"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0"
publish = false

[[bin]]
name = "chameleon"
path = "src/main.rs"

[[bin]]
name = "chameleon-worker"
path = "src/worker.rs"

[dependencies.actix-web]
version = "4.2.1"

[dependencies.actix-cors]
version = "0.6.4"

[dependencies.serde]
version = "1.0.147"
features = ["derive"]

[dependencies.serde_json]
version = "1.0.89"

[dependencies.serde_qs]
version = "0.10.1"

[dependencies.config]
version = "0.13.2"

[dependencies.lazy_static]
version = "1.4.0"

[dependencies.sqlx]
version = "0.6.2"
features = [
  "runtime-tokio-rustls",
  "postgres",
  "chrono",
  "macros",
  "migrate",
  "uuid",
  "json",
]

[dependencies.env_logger]
version = "0.9.3"

[dependencies.log]
version = "0.4.17"

[dependencies.strum]
version = "0.24.1"
features = ["derive"]

[dependencies.strum_macros]
version = "0.24.1"

[dependencies.chrono]
version = "0.4.23"
features = ["clock", "std", "wasmbind", "serde"]
default-features = false

[dependencies.async-trait]
version = "0.1.58"

[dependencies.tokio]
version = "1.22.0"
features = ["macros", "process"]

[dependencies.actix-easy-multipart]
version = "3.0.0"

[dependencies.uuid]
version = "1.2.2"
features = ["std", "serde", "v4"]

[dependencies.num-traits]
version = "0.2"

[dependencies.once_cell]
version = "1.16.0"

[dependencies.mime]
version = "0.3.16"

[dependencies.aws-types]
version = "0.51.0"

[dependencies.aws-config]
version = "0.51.0"

[dependencies.aws-sdk-s3]
version = "0.21.0"

[dependencies.aws-sdk-sqs]
version = "0.21.0"

[dependencies.jsonwebtoken]
version = "8.1.1"

[dependencies.sha2]
version = "0.10.6"

[dependencies.hex]
version = "0.4.3"

[dependencies.rand]
version = "0.8.5"

[dependencies.futures-util]
version = "0.3.25"

[dependencies.handlebars]
version = "4.3.5"

[dependencies.argon2]
version = "0.4.1"

[dependencies.markdown]
version = "1.0.0-alpha.3"

[dependencies.tempfile]
version = "3.3.0"

[dependencies.aws-smithy-http]
version = "0.51.0"

[dependencies.blurhash]
version = "0.1.1"

[dependencies.image]
version = "0.24.5"

[dependencies.utoipa]
version = "2.4.1"
features = ["actix_extras", "chrono", "uuid", "json"]

[dependencies.utoipa-swagger-ui]
version = "2.0.2"
features = ["actix-web"]

[dev-dependencies.mockall]
version = "0.11.3"
